version: '3.6' 
services: 
    # MySQL
    db:
        image: edumar111/mysql-service:1.0.0
        container_name: ms-mysql-service-svc
        restart: always
        ports:
         - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: rootpw
            MYSQL_DATABASE: customerDB
            MYSQL_USER: user_store
            MYSQL_PASSWORD: password_store
        networks:
            - onlinestore
        volumes: 
            - mysqldata:/var/lib/mysql
    redis-service:
        image: edumar111/redis-service:1.0.0
        container_name: ms-redis-service-svc
        ports:
        - 8087:8087
        networks:
        - onlinestore
    zipkin:
        image: openzipkin/zipkin:2
        container_name: ms-zipkin-service-svc
        ports:
        - "9411:9411"
    config-service:
        image: edumar111/config-service:1.0.0
        container_name: ms-config-backend-svc
        environment:
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        - GIT_USER=$GIT_USER
        - GIT_PASSWORD=$GIT_PASSWORD
        ports:
        - 8081:8081
        networks:
        - onlinestore
networks:
    onlinestore:
        external: true
volumes:
  mysqldata:
    external: true