spring:
  profiles:
    active: dev
  application:
    name: ms-customer
  cloud:
    config:
      retry:
        initial-interval: 3000
        max-attempts: 8
        max-interval: 20000
        multiplier: 1.1
  rabbitmq:
    host: ms-rabbitmq-service-svc
    port: 5672
    username: guest
    password: guest
  zipkin:
    baseUrl: http://ms-zipkin-service-svc:9411
management:
  endpoints:
    web:
      exposure:
        include: "*"
---
# https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.5-Release-Notes
#-Dfile.encoding=UTF-8
#Application Configuration
server:
  port: 18092
  error:
    include-message: always
    include-binding-errors: always
# To See H2 Console in Browser:
# http://localhost:8092/h2-console
# Enabling H2 Console
spring:
  config:
    activate:
      on-profile: local
  h2:
    console:
      enabled: true
  # ===============================
  # DB
  # ===============================
  datasource:
    url: jdbc:h2:mem:customerDB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    platform: h2
    username: sa
    password:

  # ===============================
  # JPA / HIBERNATE
  # ===============================
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/